name: Keep Render App Active

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -m 10 https://assignment-frontend-dz43.onrender.com || echo "Render app ping failed"
