name: Keep Render App Active

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: curl -m 10 https://api.render.com/deploy/srv-cvb623trie7s739c1tog?key=S82qyJPSHIs || echo "Render app ping failed"
